spring:
  profiles:
    active: default
---

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/woo
    username: yh
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: false
        format_sql: true

logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace

server:
  port: 8081
