#https://velog.io/@swchoi0329/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0%EC%99%80-OAuth-2.0%EC%9C%BC%EB%A1%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84
#https://docs.spring.io/spring-security/site/docs/5.3.5.BUILD-SNAPSHOT/reference/html5/#oauth2login-boot-property-mappings
#https://codecrafting.tistory.com/16
#https://sundries-in-myidea.tistory.com/93
#https://docs.spring.io/spring-security/site/docs/5.3.5.BUILD-SNAPSHOT/reference/html5/#oauth2login-sample-boot
#https://www.baeldung.com/spring-security-5-oauth2-login

#http://yoonbumtae.com/?p=2652 spring server side
#http://yoonbumtae.com/?p=3000 spa로 인증
#https://engkimbs.tistory.com/849 카카오
#https://kakao-tam.tistory.com/54 카카오

#네이버 공식
#https://developers.naver.com/docs/login/devguide/devguide.md#3-4-2-%EB%84%A4%EC%95%84%EB%A1%9C-%EC%97%B0%EB%8F%99-url-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0

#domain model everywhere


#ClientRegistration 속성 설정
#각 벤더사의 기본 설정값은 CommonOAuth2Provider 참고
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile,email
          github:
            client-id:
            client-secret:
          naver:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            #https://developers.kakao.com/console/app/452133/product/login/scope
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            #스프링 시큐리티에선 하위 필드를 명시 할 수 없습니다. 최상위 필드들만 user_name으로 지정가능합니다. 그래서 id 대신 response
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
